-- Generated by Oracle SQL Developer Data Modeler 21.2.0.183.1957
--   at:        2021-09-08 19:20:25 ICT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE faskes (
    id_instansi       VARCHAR2(7) NOT NULL,
    nama_instansi     VARCHAR2(50) NOT NULL,
    alamat_instansi   VARCHAR2(100) NOT NULL,
    kota_instansi     VARCHAR2(50) NOT NULL,
    provinsi_instansi VARCHAR2(50) NOT NULL,
    nakes_nip         NUMBER
);

CREATE INDEX faskes__idx ON
    faskes (
        nakes_nip
    ASC );

ALTER TABLE faskes ADD CONSTRAINT faskes_pk PRIMARY KEY ( id_instansi );

CREATE TABLE laporan (
    id_laporan VARCHAR2(6) NOT NULL,
    nakes_nip  NUMBER(20)
);

ALTER TABLE laporan ADD CONSTRAINT laporan_pk PRIMARY KEY ( id_laporan );

CREATE TABLE nakes (
    nip                NUMBER(20) NOT NULL,
    nama_lengkap_nakes VARCHAR2(50) NOT NULL,
    jk_nakes           CHAR(1) NOT NULL,
    alamat_nakes       VARCHAR2(100) NOT NULL,
    kota_nakes         VARCHAR2(50) NOT NULL,
    provinsi_nakes     VARCHAR2(50) NOT NULL,
    email_nakes        VARCHAR2(50) NOT NULL,
    no_hp_nakes        NUMBER(15) NOT NULL,
    jabatan            VARCHAR2(50) NOT NULL,
    user_id_user       VARCHAR2(5) NOT NULL,
    faskes_id_instansi VARCHAR2(7)
);

CREATE UNIQUE INDEX nakes__idx ON
    nakes (
        user_id_user
    ASC );

ALTER TABLE nakes ADD CONSTRAINT nakes_pk PRIMARY KEY ( nip );

CREATE TABLE person (
    nik                 NUMBER(20) NOT NULL,
    nama_lengkap        CHAR(50) NOT NULL,
    jk                  CHAR(1) NOT NULL,
    tgl_lahir           DATE NOT NULL,
    alamat              VARCHAR2(100) NOT NULL,
    kota                VARCHAR2(50) NOT NULL,
    provinsi            VARCHAR2(50) NOT NULL,
    email               VARCHAR2(50) NOT NULL,
    no_hp               NUMBER(15) NOT NULL,
    vaksinasi_id_regist NUMBER(5)
);

ALTER TABLE person ADD CONSTRAINT person_pk PRIMARY KEY ( nik );

CREATE TABLE "USER" (
    id_user          VARCHAR2(5) NOT NULL,
    username         VARCHAR2(20) NOT NULL,
    password         VARCHAR2(8) NOT NULL,
    user_role        VARCHAR2(10) NOT NULL,
    status           VARCHAR2(1) NOT NULL,
    confirm_password VARCHAR2(8) NOT NULL,
    nakes_nip        NUMBER(20) NOT NULL
);

CREATE UNIQUE INDEX user__idx ON
    "USER" (
        nakes_nip
    ASC );

ALTER TABLE "USER" ADD CONSTRAINT user_pk PRIMARY KEY ( id_user );

CREATE TABLE vaksin (
    id_vaksin             VARCHAR2(5) NOT NULL,
    jenis_vaksin          VARCHAR2(25) NOT NULL,
    tgl_terima_vaksin     DATE NOT NULL,
    tgl_kadaluarsa_vaksin DATE NOT NULL,
    jml_vaksin_tersedia   NUMBER(5) NOT NULL,
    faskes_id_instansi    VARCHAR2(7)
);

ALTER TABLE vaksin ADD CONSTRAINT vaksin_pk PRIMARY KEY ( id_vaksin );

CREATE TABLE vaksinasi (
    id_regist          NUMBER(5) NOT NULL,
    tgl_vaksin         DATE NOT NULL,
    diagnosa           VARCHAR2(50) NOT NULL,
    dosis_vaksin       NUMBER(5) NOT NULL,
    nik                NUMBER,
    faskes_id_instansi VARCHAR2(7)
);

CREATE INDEX vaksinasi__idx ON
    vaksinasi (
        nik
    ASC );

CREATE INDEX vaksinasi__idx2 ON
    vaksinasi (
        faskes_id_instansi
    ASC );

ALTER TABLE vaksinasi ADD CONSTRAINT vaksinasi_pk PRIMARY KEY ( id_regist );

ALTER TABLE laporan
    ADD CONSTRAINT laporan_nakes_fk FOREIGN KEY ( nakes_nip )
        REFERENCES nakes ( nip );

ALTER TABLE nakes
    ADD CONSTRAINT nakes_faskes_fk FOREIGN KEY ( faskes_id_instansi )
        REFERENCES faskes ( id_instansi );

ALTER TABLE nakes
    ADD CONSTRAINT nakes_user_fk FOREIGN KEY ( user_id_user )
        REFERENCES "USER" ( id_user );

ALTER TABLE person
    ADD CONSTRAINT person_vaksinasi_fk FOREIGN KEY ( vaksinasi_id_regist )
        REFERENCES vaksinasi ( id_regist );

ALTER TABLE "USER"
    ADD CONSTRAINT user_nakes_fk FOREIGN KEY ( nakes_nip )
        REFERENCES nakes ( nip );

ALTER TABLE vaksin
    ADD CONSTRAINT vaksin_faskes_fk FOREIGN KEY ( faskes_id_instansi )
        REFERENCES faskes ( id_instansi );

ALTER TABLE vaksinasi
    ADD CONSTRAINT vaksinasi_faskes_fk FOREIGN KEY ( faskes_id_instansi )
        REFERENCES faskes ( id_instansi );

CREATE SEQUENCE vaksinasi_id_regist_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER vaksinasi_id_regist_trg BEFORE
    INSERT ON vaksinasi
    FOR EACH ROW
    WHEN ( new.id_regist IS NULL )
BEGIN
    :new.id_regist := vaksinasi_id_regist_seq.nextval;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             5
-- ALTER TABLE                             14
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           1
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          1
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
